name: tf_gpu
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=10.1
  - cuDNN=7.6
  - opencv 
  - scipy 
  - numpy 
  - matplotlib
  - scikit-learn
  - scikit-image
  - pandas
  - pip:
    - tensorflow_gpu==2.3

